spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQuFRk83dsCmVxCwESL
      secret-key: X6HGL19FYxmNUHNe9Z02DM4BUVS5Eo
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: gulimall-thirdpart

server:
  port: 30000
